// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package dcrticketmatcher is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	TxOut
	TxIn
	OutPoint
	FindMatchesRequest
	FindMatchesResponse
	GenerateTicketRequest
	GenerateTicketResponse
	FundTicketRequest
	FundTicketResponse
	FundSplitTxRequest
	FundSplitTxResponse
	StatusRequest
	StatusResponse
*/
package dcrticketmatcher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxOut struct {
	Value  uint64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Script []byte `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
}

func (m *TxOut) Reset()                    { *m = TxOut{} }
func (m *TxOut) String() string            { return proto.CompactTextString(m) }
func (*TxOut) ProtoMessage()               {}
func (*TxOut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TxOut) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TxOut) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type TxIn struct {
	PrevHash  []byte `protobuf:"bytes,1,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	PrevIndex int32  `protobuf:"varint,2,opt,name=prev_index,json=prevIndex" json:"prev_index,omitempty"`
	ScriptSig []byte `protobuf:"bytes,3,opt,name=script_sig,json=scriptSig,proto3" json:"script_sig,omitempty"`
}

func (m *TxIn) Reset()                    { *m = TxIn{} }
func (m *TxIn) String() string            { return proto.CompactTextString(m) }
func (*TxIn) ProtoMessage()               {}
func (*TxIn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TxIn) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *TxIn) GetPrevIndex() int32 {
	if m != nil {
		return m.PrevIndex
	}
	return 0
}

func (m *TxIn) GetScriptSig() []byte {
	if m != nil {
		return m.ScriptSig
	}
	return nil
}

type OutPoint struct {
	PrevHash  []byte `protobuf:"bytes,1,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	PrevIndex int32  `protobuf:"varint,2,opt,name=prev_index,json=prevIndex" json:"prev_index,omitempty"`
	Tree      int32  `protobuf:"varint,3,opt,name=tree" json:"tree,omitempty"`
}

func (m *OutPoint) Reset()                    { *m = OutPoint{} }
func (m *OutPoint) String() string            { return proto.CompactTextString(m) }
func (*OutPoint) ProtoMessage()               {}
func (*OutPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OutPoint) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *OutPoint) GetPrevIndex() int32 {
	if m != nil {
		return m.PrevIndex
	}
	return 0
}

func (m *OutPoint) GetTree() int32 {
	if m != nil {
		return m.Tree
	}
	return 0
}

type FindMatchesRequest struct {
	Amount uint64 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
}

func (m *FindMatchesRequest) Reset()                    { *m = FindMatchesRequest{} }
func (m *FindMatchesRequest) String() string            { return proto.CompactTextString(m) }
func (*FindMatchesRequest) ProtoMessage()               {}
func (*FindMatchesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FindMatchesRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type FindMatchesResponse struct {
	SessionId int32  `protobuf:"varint,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Amount    uint64 `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Fee       uint64 `protobuf:"varint,3,opt,name=fee" json:"fee,omitempty"`
}

func (m *FindMatchesResponse) Reset()                    { *m = FindMatchesResponse{} }
func (m *FindMatchesResponse) String() string            { return proto.CompactTextString(m) }
func (*FindMatchesResponse) ProtoMessage()               {}
func (*FindMatchesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FindMatchesResponse) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *FindMatchesResponse) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *FindMatchesResponse) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type GenerateTicketRequest struct {
	SessionId        int32       `protobuf:"varint,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	CommitmentOutput *TxOut      `protobuf:"bytes,2,opt,name=commitment_output,json=commitmentOutput" json:"commitment_output,omitempty"`
	ChangeOutput     *TxOut      `protobuf:"bytes,3,opt,name=change_output,json=changeOutput" json:"change_output,omitempty"`
	SplitTxOutput    *TxOut      `protobuf:"bytes,4,opt,name=split_tx_output,json=splitTxOutput" json:"split_tx_output,omitempty"`
	SplitTxChange    *TxOut      `protobuf:"bytes,5,opt,name=split_tx_change,json=splitTxChange" json:"split_tx_change,omitempty"`
	SplitTxInputs    []*OutPoint `protobuf:"bytes,6,rep,name=split_tx_inputs,json=splitTxInputs" json:"split_tx_inputs,omitempty"`
	VoteAddress      string      `protobuf:"bytes,7,opt,name=vote_address,json=voteAddress" json:"vote_address,omitempty"`
}

func (m *GenerateTicketRequest) Reset()                    { *m = GenerateTicketRequest{} }
func (m *GenerateTicketRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateTicketRequest) ProtoMessage()               {}
func (*GenerateTicketRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GenerateTicketRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *GenerateTicketRequest) GetCommitmentOutput() *TxOut {
	if m != nil {
		return m.CommitmentOutput
	}
	return nil
}

func (m *GenerateTicketRequest) GetChangeOutput() *TxOut {
	if m != nil {
		return m.ChangeOutput
	}
	return nil
}

func (m *GenerateTicketRequest) GetSplitTxOutput() *TxOut {
	if m != nil {
		return m.SplitTxOutput
	}
	return nil
}

func (m *GenerateTicketRequest) GetSplitTxChange() *TxOut {
	if m != nil {
		return m.SplitTxChange
	}
	return nil
}

func (m *GenerateTicketRequest) GetSplitTxInputs() []*OutPoint {
	if m != nil {
		return m.SplitTxInputs
	}
	return nil
}

func (m *GenerateTicketRequest) GetVoteAddress() string {
	if m != nil {
		return m.VoteAddress
	}
	return ""
}

type GenerateTicketResponse struct {
	Ticket     []byte `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	SplitTx    []byte `protobuf:"bytes,2,opt,name=split_tx,json=splitTx,proto3" json:"split_tx,omitempty"`
	Revocation []byte `protobuf:"bytes,3,opt,name=revocation,proto3" json:"revocation,omitempty"`
}

func (m *GenerateTicketResponse) Reset()                    { *m = GenerateTicketResponse{} }
func (m *GenerateTicketResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateTicketResponse) ProtoMessage()               {}
func (*GenerateTicketResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GenerateTicketResponse) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func (m *GenerateTicketResponse) GetSplitTx() []byte {
	if m != nil {
		return m.SplitTx
	}
	return nil
}

func (m *GenerateTicketResponse) GetRevocation() []byte {
	if m != nil {
		return m.Revocation
	}
	return nil
}

type FundTicketRequest struct {
	SessionId            int32  `protobuf:"varint,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	TicketInputScriptsig []byte `protobuf:"bytes,2,opt,name=ticket_input_scriptsig,json=ticketInputScriptsig,proto3" json:"ticket_input_scriptsig,omitempty"`
}

func (m *FundTicketRequest) Reset()                    { *m = FundTicketRequest{} }
func (m *FundTicketRequest) String() string            { return proto.CompactTextString(m) }
func (*FundTicketRequest) ProtoMessage()               {}
func (*FundTicketRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FundTicketRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *FundTicketRequest) GetTicketInputScriptsig() []byte {
	if m != nil {
		return m.TicketInputScriptsig
	}
	return nil
}

type FundTicketResponse struct {
	Ticket []byte `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (m *FundTicketResponse) Reset()                    { *m = FundTicketResponse{} }
func (m *FundTicketResponse) String() string            { return proto.CompactTextString(m) }
func (*FundTicketResponse) ProtoMessage()               {}
func (*FundTicketResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FundTicketResponse) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type FundSplitTxRequest struct {
	SessionId         int32    `protobuf:"varint,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	SplitTxScriptsigs [][]byte `protobuf:"bytes,2,rep,name=split_tx_scriptsigs,json=splitTxScriptsigs,proto3" json:"split_tx_scriptsigs,omitempty"`
}

func (m *FundSplitTxRequest) Reset()                    { *m = FundSplitTxRequest{} }
func (m *FundSplitTxRequest) String() string            { return proto.CompactTextString(m) }
func (*FundSplitTxRequest) ProtoMessage()               {}
func (*FundSplitTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FundSplitTxRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *FundSplitTxRequest) GetSplitTxScriptsigs() [][]byte {
	if m != nil {
		return m.SplitTxScriptsigs
	}
	return nil
}

type FundSplitTxResponse struct {
	SplitTx []byte `protobuf:"bytes,1,opt,name=split_tx,json=splitTx,proto3" json:"split_tx,omitempty"`
}

func (m *FundSplitTxResponse) Reset()                    { *m = FundSplitTxResponse{} }
func (m *FundSplitTxResponse) String() string            { return proto.CompactTextString(m) }
func (*FundSplitTxResponse) ProtoMessage()               {}
func (*FundSplitTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *FundSplitTxResponse) GetSplitTx() []byte {
	if m != nil {
		return m.SplitTx
	}
	return nil
}

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type StatusResponse struct {
	TicketPrice uint64 `protobuf:"varint,1,opt,name=ticket_price,json=ticketPrice" json:"ticket_price,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *StatusResponse) GetTicketPrice() uint64 {
	if m != nil {
		return m.TicketPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*TxOut)(nil), "dcrticketmatcher.TxOut")
	proto.RegisterType((*TxIn)(nil), "dcrticketmatcher.TxIn")
	proto.RegisterType((*OutPoint)(nil), "dcrticketmatcher.OutPoint")
	proto.RegisterType((*FindMatchesRequest)(nil), "dcrticketmatcher.FindMatchesRequest")
	proto.RegisterType((*FindMatchesResponse)(nil), "dcrticketmatcher.FindMatchesResponse")
	proto.RegisterType((*GenerateTicketRequest)(nil), "dcrticketmatcher.GenerateTicketRequest")
	proto.RegisterType((*GenerateTicketResponse)(nil), "dcrticketmatcher.GenerateTicketResponse")
	proto.RegisterType((*FundTicketRequest)(nil), "dcrticketmatcher.FundTicketRequest")
	proto.RegisterType((*FundTicketResponse)(nil), "dcrticketmatcher.FundTicketResponse")
	proto.RegisterType((*FundSplitTxRequest)(nil), "dcrticketmatcher.FundSplitTxRequest")
	proto.RegisterType((*FundSplitTxResponse)(nil), "dcrticketmatcher.FundSplitTxResponse")
	proto.RegisterType((*StatusRequest)(nil), "dcrticketmatcher.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "dcrticketmatcher.StatusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SplitTicketMatcherService service

type SplitTicketMatcherServiceClient interface {
	FindMatches(ctx context.Context, in *FindMatchesRequest, opts ...grpc.CallOption) (*FindMatchesResponse, error)
	GenerateTicket(ctx context.Context, in *GenerateTicketRequest, opts ...grpc.CallOption) (*GenerateTicketResponse, error)
	FundTicket(ctx context.Context, in *FundTicketRequest, opts ...grpc.CallOption) (*FundTicketResponse, error)
	FundSplitTx(ctx context.Context, in *FundSplitTxRequest, opts ...grpc.CallOption) (*FundSplitTxResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type splitTicketMatcherServiceClient struct {
	cc *grpc.ClientConn
}

func NewSplitTicketMatcherServiceClient(cc *grpc.ClientConn) SplitTicketMatcherServiceClient {
	return &splitTicketMatcherServiceClient{cc}
}

func (c *splitTicketMatcherServiceClient) FindMatches(ctx context.Context, in *FindMatchesRequest, opts ...grpc.CallOption) (*FindMatchesResponse, error) {
	out := new(FindMatchesResponse)
	err := grpc.Invoke(ctx, "/dcrticketmatcher.SplitTicketMatcherService/FindMatches", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *splitTicketMatcherServiceClient) GenerateTicket(ctx context.Context, in *GenerateTicketRequest, opts ...grpc.CallOption) (*GenerateTicketResponse, error) {
	out := new(GenerateTicketResponse)
	err := grpc.Invoke(ctx, "/dcrticketmatcher.SplitTicketMatcherService/GenerateTicket", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *splitTicketMatcherServiceClient) FundTicket(ctx context.Context, in *FundTicketRequest, opts ...grpc.CallOption) (*FundTicketResponse, error) {
	out := new(FundTicketResponse)
	err := grpc.Invoke(ctx, "/dcrticketmatcher.SplitTicketMatcherService/FundTicket", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *splitTicketMatcherServiceClient) FundSplitTx(ctx context.Context, in *FundSplitTxRequest, opts ...grpc.CallOption) (*FundSplitTxResponse, error) {
	out := new(FundSplitTxResponse)
	err := grpc.Invoke(ctx, "/dcrticketmatcher.SplitTicketMatcherService/FundSplitTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *splitTicketMatcherServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/dcrticketmatcher.SplitTicketMatcherService/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SplitTicketMatcherService service

type SplitTicketMatcherServiceServer interface {
	FindMatches(context.Context, *FindMatchesRequest) (*FindMatchesResponse, error)
	GenerateTicket(context.Context, *GenerateTicketRequest) (*GenerateTicketResponse, error)
	FundTicket(context.Context, *FundTicketRequest) (*FundTicketResponse, error)
	FundSplitTx(context.Context, *FundSplitTxRequest) (*FundSplitTxResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

func RegisterSplitTicketMatcherServiceServer(s *grpc.Server, srv SplitTicketMatcherServiceServer) {
	s.RegisterService(&_SplitTicketMatcherService_serviceDesc, srv)
}

func _SplitTicketMatcherService_FindMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitTicketMatcherServiceServer).FindMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dcrticketmatcher.SplitTicketMatcherService/FindMatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitTicketMatcherServiceServer).FindMatches(ctx, req.(*FindMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SplitTicketMatcherService_GenerateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitTicketMatcherServiceServer).GenerateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dcrticketmatcher.SplitTicketMatcherService/GenerateTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitTicketMatcherServiceServer).GenerateTicket(ctx, req.(*GenerateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SplitTicketMatcherService_FundTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitTicketMatcherServiceServer).FundTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dcrticketmatcher.SplitTicketMatcherService/FundTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitTicketMatcherServiceServer).FundTicket(ctx, req.(*FundTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SplitTicketMatcherService_FundSplitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundSplitTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitTicketMatcherServiceServer).FundSplitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dcrticketmatcher.SplitTicketMatcherService/FundSplitTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitTicketMatcherServiceServer).FundSplitTx(ctx, req.(*FundSplitTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SplitTicketMatcherService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitTicketMatcherServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dcrticketmatcher.SplitTicketMatcherService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitTicketMatcherServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SplitTicketMatcherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dcrticketmatcher.SplitTicketMatcherService",
	HandlerType: (*SplitTicketMatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMatches",
			Handler:    _SplitTicketMatcherService_FindMatches_Handler,
		},
		{
			MethodName: "GenerateTicket",
			Handler:    _SplitTicketMatcherService_GenerateTicket_Handler,
		},
		{
			MethodName: "FundTicket",
			Handler:    _SplitTicketMatcherService_FundTicket_Handler,
		},
		{
			MethodName: "FundSplitTx",
			Handler:    _SplitTicketMatcherService_FundSplitTx_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _SplitTicketMatcherService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x55, 0x97, 0xb6, 0x5b, 0x6f, 0xbb, 0x7f, 0xde, 0x7e, 0xfd, 0x65, 0x45, 0x40, 0x67, 0x86,
	0xe8, 0x03, 0xaa, 0xd0, 0x06, 0x6f, 0x48, 0x88, 0x3f, 0x1a, 0x54, 0x08, 0x6d, 0x4a, 0x27, 0x21,
	0xed, 0x81, 0xc8, 0x24, 0x66, 0xb1, 0xb6, 0x3a, 0xc1, 0x76, 0xaa, 0x7e, 0x1f, 0xbe, 0x17, 0x9f,
	0x05, 0xc5, 0x76, 0xba, 0xa4, 0xed, 0xda, 0x21, 0xde, 0xe2, 0xe3, 0x7b, 0xce, 0xb9, 0xbe, 0xf7,
	0xda, 0x81, 0x06, 0x49, 0x58, 0x3f, 0x11, 0xb1, 0x8a, 0xd1, 0x4e, 0x18, 0x08, 0xc5, 0x82, 0x6b,
	0xaa, 0x46, 0x44, 0x05, 0x11, 0x15, 0xf8, 0x15, 0xd4, 0x2e, 0x26, 0x67, 0xa9, 0x42, 0xfb, 0x50,
	0x1b, 0x93, 0x9b, 0x94, 0xba, 0x95, 0x6e, 0xa5, 0x57, 0xf5, 0xcc, 0x02, 0xb5, 0xa1, 0x2e, 0x03,
	0xc1, 0x12, 0xe5, 0xae, 0x75, 0x2b, 0xbd, 0x96, 0x67, 0x57, 0x98, 0x40, 0xf5, 0x62, 0x32, 0xe0,
	0xe8, 0x01, 0x34, 0x12, 0x41, 0xc7, 0x7e, 0x44, 0x64, 0xa4, 0x99, 0x2d, 0x6f, 0x23, 0x03, 0x3e,
	0x11, 0x19, 0xa1, 0x87, 0x00, 0x7a, 0x93, 0xf1, 0x90, 0x4e, 0xb4, 0x40, 0xcd, 0xd3, 0xe1, 0x83,
	0x0c, 0xc8, 0xb6, 0x8d, 0x9a, 0x2f, 0xd9, 0x95, 0xeb, 0x68, 0x72, 0xc3, 0x20, 0x43, 0x76, 0x85,
	0x2f, 0x61, 0xe3, 0x2c, 0x55, 0xe7, 0x31, 0xe3, 0xea, 0x9f, 0x6c, 0x10, 0x54, 0x95, 0xa0, 0x54,
	0x1b, 0xd4, 0x3c, 0xfd, 0x8d, 0x9f, 0x03, 0x3a, 0x65, 0x3c, 0xfc, 0xa2, 0x8b, 0x20, 0x3d, 0xfa,
	0x33, 0xa5, 0x52, 0x65, 0x87, 0x25, 0xa3, 0x38, 0xe5, 0xca, 0xd6, 0xc0, 0xae, 0xf0, 0x37, 0xd8,
	0x2b, 0x45, 0xcb, 0x24, 0xe6, 0x92, 0xea, 0xfc, 0xa9, 0x94, 0x2c, 0xe6, 0x3e, 0x0b, 0x35, 0xa5,
	0xe6, 0x35, 0x2c, 0x32, 0x08, 0x0b, 0x6a, 0x6b, 0x45, 0x35, 0xb4, 0x03, 0xce, 0x0f, 0x9b, 0x4e,
	0xd5, 0xcb, 0x3e, 0xf1, 0x2f, 0x07, 0xfe, 0xfb, 0x48, 0x39, 0x15, 0x44, 0xd1, 0x0b, 0xdd, 0x9d,
	0x3c, 0xa3, 0x15, 0x16, 0x1f, 0x60, 0x37, 0x88, 0x47, 0x23, 0xa6, 0x46, 0x94, 0x2b, 0x3f, 0x4e,
	0x55, 0x92, 0x1a, 0xb7, 0xe6, 0xf1, 0xff, 0xfd, 0xd9, 0x56, 0xf7, 0x75, 0x9f, 0xbd, 0x9d, 0x5b,
	0xc6, 0x99, 0x26, 0xa0, 0xd7, 0xb0, 0x19, 0x44, 0x84, 0x5f, 0xd1, 0x5c, 0xc1, 0x59, 0xae, 0xd0,
	0x32, 0xd1, 0x96, 0xfd, 0x06, 0xb6, 0x65, 0x72, 0xc3, 0x94, 0xaf, 0x26, 0x39, 0xbf, 0xba, 0x9c,
	0xbf, 0xa9, 0xe3, 0xf5, 0xf7, 0xac, 0x80, 0x51, 0x76, 0x6b, 0xf7, 0x13, 0x78, 0xaf, 0xa3, 0xd1,
	0xbb, 0x82, 0x00, 0xe3, 0x49, 0xaa, 0xa4, 0x5b, 0xef, 0x3a, 0xbd, 0xe6, 0x71, 0x67, 0x5e, 0x20,
	0x9f, 0xa8, 0xa9, 0xc6, 0x40, 0x13, 0xd0, 0x21, 0xb4, 0xc6, 0xb1, 0xa2, 0x3e, 0x09, 0x43, 0x41,
	0xa5, 0x74, 0xd7, 0xbb, 0x95, 0x5e, 0xc3, 0x6b, 0x66, 0xd8, 0x5b, 0x03, 0xe1, 0x6b, 0x68, 0xcf,
	0x36, 0xc9, 0x0e, 0x42, 0x1b, 0xea, 0xc6, 0xc5, 0x8e, 0xa6, 0x5d, 0xa1, 0x03, 0xd8, 0xc8, 0x13,
	0xb3, 0xd7, 0x67, 0xdd, 0xba, 0xa2, 0x47, 0x00, 0x82, 0x8e, 0xe3, 0x80, 0x28, 0x16, 0x73, 0x3b,
	0xfb, 0x05, 0x04, 0x47, 0xb0, 0x7b, 0x9a, 0xf2, 0xf0, 0xaf, 0xa6, 0xe1, 0x25, 0xb4, 0x8d, 0xb1,
	0xa9, 0x82, 0x6f, 0xae, 0x52, 0x76, 0xb7, 0x8c, 0xf9, 0xbe, 0xd9, 0xd5, 0x27, 0x1e, 0xe6, 0x7b,
	0xfa, 0x2a, 0x14, 0x9c, 0x96, 0x1f, 0x09, 0x07, 0x26, 0x7a, 0x68, 0x8e, 0x71, 0xcf, 0xc4, 0xfa,
	0xb0, 0x37, 0x6d, 0xd0, 0x34, 0x29, 0xe9, 0xae, 0x75, 0x9d, 0x5e, 0xcb, 0xdb, 0xb5, 0x25, 0x99,
	0x66, 0x24, 0xf1, 0x0b, 0xd8, 0x2b, 0x99, 0xd8, 0x9c, 0x8a, 0xe5, 0xac, 0x94, 0xca, 0x89, 0xb7,
	0x61, 0x73, 0xa8, 0x88, 0x4a, 0xf3, 0xab, 0x8c, 0x4f, 0x60, 0x2b, 0x07, 0x2c, 0xfb, 0x10, 0x5a,
	0xb6, 0x3a, 0x89, 0x60, 0x41, 0xfe, 0xcc, 0x35, 0x0d, 0x76, 0x9e, 0x41, 0xc7, 0xbf, 0x1d, 0x38,
	0x30, 0xa6, 0x1a, 0x34, 0xf7, 0x5d, 0x0c, 0xa9, 0x18, 0xb3, 0x80, 0xa2, 0x4b, 0x68, 0x16, 0x5e,
	0x01, 0x74, 0x34, 0x3f, 0x5c, 0xf3, 0x4f, 0x4a, 0xe7, 0xe9, 0x8a, 0x28, 0x9b, 0x5c, 0x00, 0x5b,
	0xe5, 0xd9, 0x42, 0xcf, 0xe6, 0x89, 0x0b, 0x9f, 0x88, 0x4e, 0x6f, 0x75, 0xa0, 0x35, 0xf9, 0x0a,
	0x70, 0xdb, 0x69, 0xf4, 0x64, 0x41, 0x66, 0xb3, 0x13, 0xd7, 0x39, 0x5a, 0x1e, 0x64, 0x85, 0xb3,
	0xca, 0xdc, 0xf6, 0x0b, 0xdd, 0x41, 0x2a, 0xcf, 0xcc, 0xc2, 0xca, 0x2c, 0x68, 0xfa, 0x67, 0xa8,
	0x9b, 0x46, 0xa2, 0xc7, 0xf3, 0x84, 0x52, 0xcf, 0x3b, 0xdd, 0xbb, 0x03, 0x8c, 0xd8, 0xf7, 0xba,
	0xfe, 0x0b, 0x9e, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x83, 0x67, 0x0c, 0x12, 0x07, 0x00,
	0x00,
}
