# copied from decred/dcrd
language: go
go:
  - 1.x

sudo: required
services:
  - docker

env:
  - GOVERSION=1.11

install: true

cache:
  directories:
    - ~/.cache

script:
  - ./run_tests.sh $GOVERSION
