# copied from decred/dcrd

branches:
  only:
    - master

language: go
go:
  - 1.x

sudo: required
services:
  - docker

env:
  - GOVERSION=1.11 INSTALL_GOMETALINTER_TOOLS=1

install: true

cache:
  directories:
    - ~/.cache

script: ./run_tests.sh $GOVERSION
