#matheusd-dcr-split-tickets
# This image may be called with the run_tests.sh script included in any of the
# supported go repos.
# ./run_tests.sh 1.10

FROM golang:1.10.2

LABEL description="Decred split tickets builder image"
LABEL version="1.0"
LABEL maintainer "docker-ops@matheusd.org"

ENV TERM linux
ENV USER build

# create user
RUN adduser --disabled-password --gecos ''  $USER

# update base distro & install build tooling
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -qy rsync git libgtk2.0-dev libglib2.0-dev libgtksourceview2.0-dev

# create directory for build artifacts, adjust user permissions
RUN mkdir /release && \
    chown $USER /release

# create directory to get source from
RUN mkdir /src && \
    chown $USER /src && \
    mkdir -p /go/src/github.com/decred/dcrd && \
    mkdir -p /go/src/github.com/decred/dcrwallet && \
    mkdir -p /go/src/github.com/matheusd/dcr-split-ticket-matcher && \
    chown -R $USER /go/src

# switch user
USER $USER
ENV HOME /home/$USER

#Get deps
ENV DEP_TAG v0.4.1
ENV GOMETALINTER_TAG v2.0.5

WORKDIR /go/src
RUN go get -v github.com/alecthomas/gometalinter && \
    cd /go/src/github.com/alecthomas/gometalinter && \
    git checkout $GOMETALINTER_TAG && \
    go install -i && \
    gometalinter --install && \
    go get -v github.com/golang/dep && \
    cd /go/src/github.com/golang/dep && \
    git checkout $DEP_TAG && \
    go install -i ./...
